### PR TITLE
[FCM-81] Sleep for 30 seconds to ensure Kafka is stable

### PR DESCRIPTION
**Pull request by TimGrist**
Sleep for 60 seconds to ensure Kafka is stable

### CODE REVIEW

**Comment by dennisconrad** [comment]
Thank you for this PR!

We are already waiting for the port to appear:

```yaml
- name: Wait for Kafka port
  wait_for:
    host: "{{ sansible_kafka_listen_address }}"
```

What does waiting 30s *before* that add to this?

**Comment by wojtek-oledzki** [comment]
@dennisconrad it's for cases when Kafka does starts up, and port 9092 is available, but then due to config error Kafka dies

**Comment by dennisconrad** [comment]
That still doesn't explain why we're waiting for 30s **before** we're even checking for the port :-)  I would understand the other way round, but not like this.

Also, is there another way to ensure Kafka is ready?  Can we check a log file instead, something like...

```yaml
- name: Wait until Kafka is ready
  wait_for:
    path: /var/log/kafka/startup.log
    search_regex: "^Ready\.$"
```
?

**Comment by wojtek-oledzki** [comment]
ok, what about

```yaml
- name: Wait for Kafka port
  wait_for:
    host: "{{ sansible_kafka_listen_address }}"
    port: "{{ sansible_kafka_port }}"
    state: started
    timeout: "{{ sansible_kafka_wait_for_kafka_port }}"

- name: "Check again after {{ sansible_kafka_waitfor_delay }} seconds to ensure Kafka is stable"
  wait_for:
    delay: "{{ sansible_kafka_waitfor_delay }}"
    host: "{{ sansible_kafka_listen_address }}"
    port: "{{ sansible_kafka_port }}"
    state: started
    timeout: "{{ sansible_kafka_wait_for_kafka_port }}"
```

**Comment by dennisconrad** [comment]
How about...

```yaml
- name: Wait for Kafka port
  wait_for:
    delay: "{{ sansible_kafka_waitfor_delay }}"
    host: "{{ sansible_kafka_listen_address }}"
    port: "{{ sansible_kafka_port }}"
    state: started
    timeout: "{{ sansible_kafka_wait_for_kafka_port }}"
  with_items: [1, 2, 3]
```

1. Wait 30 seconds
2. Wait for port
3. Wait 30 seconds
4. Wait for port
5. Wait 30 seconds
6. Wait for port

If either of `2`, `4`, `6` times out, the task fails.

**Comment by TimGrist** [comment]
```
  TASK [kafka : Wait for Kafka port] *********************************************
    ok: [sansible_kafka-xenial] => (item=Initial check)
    ok: [sansible_kafka-bionic] => (item=Initial check)
    ok: [sansible_kafka-xenial] => (item=Second check)
    ok: [sansible_kafka-bionic] => (item=Second check)
```

**Pull request merged**
